openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'good name app'
servers:
  - url: 'localhost:3000'
paths:
  /indicators:
    get:
      summary: 'Возвращает список веществ'
      responses:
        '200':
          description: 'Запрос за списком веществ'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Indicator'
  /stantions:
    get:
      summary: 'Возвращает список всех станций'
      responses:
        '200':
          description: 'Запрос за станциями'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stantion'
  /data:
    get:
      summary: 'Возвращает данные по станциям, времени и веществам'
      parameters:
        - name: station_id
          in: query
          description: ID станции
          required: false
          schema:
            type: integer
            format: int64
        - name: time
          in: query
          description: время в ISO
          required: true
          schema:
            type: string
        - name: metric_name
          in: query
          description: название вещества
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Запрос за данными таймлайна'
          content:
            application/json:
              schema:
                type: object
                properties:
                  stantion:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                      time:
                        type: integer
                        format: int64
                      data:
                        type: array
                        $ref: '#/components/schemas/Indicator'
  /timeline:
    get:
      summary: 'Возвращает даты для таймлайна'
      responses:
        '200':
          description: 'Запрос за данными таймлайна'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Indicator:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        value:
          type: number
          format: float
    Stantion:
      type: object
      required:
        - id
        - name
        - latitude
        - longitude
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
    Incident:
      type: object
      required:
        - id
        - station_id
        - metric_id
        - metric_value
        - incident_type
        - incident_level
      properties:
        id:
          type: integer
          format: int64
        station_id:
          type: integer
          format: int64
        metric_id:
          type: integer
          format: int64
        metric_value:
          type: number
          format: float
        incident_type:
          type: string
        incident_level:
          type: number
